class android.support.v4.content.ModernAsyncTask$3 extends java.util.concurrent.FutureTask
{
    final android.support.v4.content.ModernAsyncTask this$0;

    void <init>(android.support.v4.content.ModernAsyncTask, java.util.concurrent.Callable)
    {
        android.support.v4.content.ModernAsyncTask$3 $r0;
        android.support.v4.content.ModernAsyncTask $r1;
        java.util.concurrent.Callable $r2;

        $r0 := @this: android.support.v4.content.ModernAsyncTask$3;

        $r1 := @parameter0: android.support.v4.content.ModernAsyncTask;

        $r2 := @parameter1: java.util.concurrent.Callable;

        $r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0> = $r1;

        specialinvoke $r0.<java.util.concurrent.FutureTask: void <init>(java.util.concurrent.Callable)>($r2);

        return;
    }

    protected void done()
    {
        android.support.v4.content.ModernAsyncTask$3 $r0;
        java.lang.Throwable $r1;
        java.lang.Object $r2;
        android.support.v4.content.ModernAsyncTask $r3;
        java.lang.InterruptedException $r4;
        java.util.concurrent.ExecutionException $r5;
        java.lang.RuntimeException $r6;
        java.util.concurrent.CancellationException $r7;

        $r0 := @this: android.support.v4.content.ModernAsyncTask$3;

     label1:
        $r2 = virtualinvoke $r0.<android.support.v4.content.ModernAsyncTask$3: java.lang.Object get()>();

     label2:
        $r3 = $r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0>;

     label3:
        staticinvoke <android.support.v4.content.ModernAsyncTask: void access$400(android.support.v4.content.ModernAsyncTask,java.lang.Object)>($r3, $r2);

     label4:
        return;

     label5:
        $r4 := @caughtexception;

        staticinvoke <android.util.Log: int w(java.lang.String,java.lang.Throwable)>("AsyncTask", $r4);

        return;

     label6:
        $r5 := @caughtexception;

        $r6 = new java.lang.RuntimeException;

        $r1 = virtualinvoke $r5.<java.util.concurrent.ExecutionException: java.lang.Throwable getCause()>();

        specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r1);

        throw $r6;

     label7:
        $r7 := @caughtexception;

        $r3 = $r0.<android.support.v4.content.ModernAsyncTask$3: android.support.v4.content.ModernAsyncTask this$0>;

        staticinvoke <android.support.v4.content.ModernAsyncTask: void access$400(android.support.v4.content.ModernAsyncTask,java.lang.Object)>($r3, null);

        return;

     label8:
        $r1 := @caughtexception;

        $r6 = new java.lang.RuntimeException;

        specialinvoke $r6.<java.lang.RuntimeException: void <init>(java.lang.String,java.lang.Throwable)>("An error occured while executing doInBackground()", $r1);

        throw $r6;

        catch java.lang.InterruptedException from label1 to label2 with label5;
        catch java.lang.InterruptedException from label3 to label4 with label5;
        catch java.util.concurrent.ExecutionException from label1 to label2 with label6;
        catch java.util.concurrent.ExecutionException from label3 to label4 with label6;
        catch java.util.concurrent.CancellationException from label1 to label2 with label7;
        catch java.util.concurrent.CancellationException from label3 to label4 with label7;
        catch java.lang.Throwable from label1 to label4 with label8;
    }
}
